---
title: Application for the Financial Support for the Study Abroad Program in Psychology 2019
author: "Koki Ikeda"
date: "September 20, 2018"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    toc: TRUE
bibliography: library.bib
# I'm using Zotero and some extensions of it
# consulting with the following site.
# http://www.janfreyberg.com/blog/2017-05-27-workflow-papers-rmarkdown/
---

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide"}
# set locale to Japanese
Sys.setlocale(category = "LC_ALL", locale = "Japanese")

# Required packages (must be executed before everything)
list.of.packages <- c("tidyr", "kableExtra", "prettydoc", "citr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(tidyr)
library(kableExtra)
```

# Overview of the Program

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
ov <- matrix(data = c("Period", "Feb. 2019 (3 weeks)",
                      "City, Country", "Brisbane, Australia",
                      "School", "[Griffith University, Nathan Campus](https://www.griffith.edu.au/about-griffith/campuses-facilities/nathan)",
                      "Number of Students", "30",
                      "Number of Recipients", "5",
                      "Year of Students", "2nd or 3rd, All from Psychology Dept.",
                      "Contents of Program", "Lecture & Research",
                      "Website", "[Chukyo University Net Campus](https://nc.chukyo-u.ac.jp/gakubu/shinri/psychology/index.html#sec_3)"),
             ncol = 2, byrow = TRUE)

# The kable function does not properly work with html_pretty
ov %>%
  kable(caption = "for the Academic Year 2019") %>%
  kable_styling(bootstrap_options = c( "bordered"),
                full_width = FALSE,
                position = "left",
                font_size = 16) %>%
  column_spec(1, width = "20em")
```

# The Goal of the Program
Humans are essentially cultural. Our lives would look fundamentally different without the culturally-transmitted knowledge, skills, and habits [@mesoudiCulturalEvolutionHow2011].

[@markusCultureSelfImplications1991]

# Reference